"
Character category for double quotes.
"
Class {
	#name : 'DoubleQuoteCharacterKindFormatterToolingRudesheim',
	#superclass : 'QuoteCharacterKindFormatterToolingRudesheim',
	#category : 'Rudesheim-Tooling-Private-CharacterKind',
	#package : 'Rudesheim-Tooling-Private',
	#tag : 'CharacterKind'
}

{ #category : 'accessing' }
DoubleQuoteCharacterKindFormatterToolingRudesheim class >> quoteCharacter [
	^ $".
]
