"
Character category for semicolons.
"
Class {
	#name : 'SemicolonCharacterKindFormatterToolingRudesheim',
	#superclass : 'PunctuationCharacterKindFormatterToolingRudesheim',
	#category : 'Rudesheim-Tooling-Private-CharacterKind',
	#package : 'Rudesheim-Tooling-Private',
	#tag : 'CharacterKind'
}

{ #category : 'accessing' }
SemicolonCharacterKindFormatterToolingRudesheim class >> character [
	^ $;.
]
