"
Character category for single quotes.
"
Class {
	#name : 'SingleQuoteCharacterKindFormatterToolingRudesheim',
	#superclass : 'QuoteCharacterKindFormatterToolingRudesheim',
	#category : 'Rudesheim-Tooling-Private-CharacterKind',
	#package : 'Rudesheim-Tooling-Private',
	#tag : 'CharacterKind'
}

{ #category : 'accessing' }
SingleQuoteCharacterKindFormatterToolingRudesheim class >> quoteCharacter [
	^ $'.
]
