"
Im namespace of the rudesheim tooling
"
Class {
	#name : 'ToolingRudesheim',
	#superclass : 'Object',
	#category : 'Rudesheim-Tooling-Namespace',
	#package : 'Rudesheim-Tooling',
	#tag : 'Namespace'
}

{ #category : 'namespace' }
ToolingRudesheim class >> CharacterKind [
	^ CharacterKindFormatterToolingRudesheim.
]

{ #category : 'namespace' }
ToolingRudesheim class >> Formatter [
	^ FormatterToolingRudesheim.
]
